In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
from sklearn.linear_model import LinearRegression
model_skl = LinearRegression()

In [3]:
from sklearn.datasets import load_boston
X, y = load_boston(return_X_y=True)

In [5]:
X.shape, y.shape

((506, 13), (506,))

In [72]:
n_train = 506
idx = np.random.permutation(506)
X_train = X[idx[0:n_train]]
X_test = X[idx[-n_train:]]
y_train = y[idx[0:n_train]]
y_test = y[idx[-n_train:]]

In [73]:
y_hat = res.predict(X_test)
r2 = (y_test - y_hat)**2

y_hat = res.predict(X_train)
r2 = (y_train - y_hat)**2

$$
    p(y_i|x_i) = \frac{1}{\sqrt{2 \pi \sigma^2}} e^{-(y_i-\hat y_i)^2/(2 \sigma^2)} 
$$

In [74]:
sigma2 = np.sum(r2) / (len(r2)-2) #Estimation of sigma
ll = -len(r2)*np.log(np.sqrt(2*np.pi*sigma2)) - np.sum((r2/(2*sigma2)))
-ll / len(r2) #NLL

2.979309285333017

In [20]:
r2

array([8.52410733e+00, 1.43095071e+00, 1.98747848e+01, 3.20831913e+01,
       3.51480336e+00, 2.51312937e+00, 4.95440594e-01, 2.11092696e+00,
       2.62266046e+01, 1.98162368e-05, 2.08527517e-02, 8.06882398e-02,
       3.64511009e-01, 4.88589435e+00, 6.02652758e-01, 1.75612053e+01,
       7.69186279e-01, 9.60046505e+00, 4.96247550e-01, 1.16008868e+02,
       1.37171744e+01, 2.89349878e+01, 1.90455684e+02, 1.57971431e+01,
       4.95925781e+01, 3.71314250e+00, 2.11342311e+02, 1.44842640e+01,
       2.04434141e+01, 2.77383485e+01, 2.10991466e+01, 1.97491894e+00,
       2.78470811e+00, 3.51282982e+01, 7.51829142e+00, 5.51351745e+00,
       2.10467893e+01, 1.32637064e+01, 2.03918475e+02, 3.48503557e+01,
       9.92183324e+00, 1.35053067e-02, 4.17608126e+00, 6.76295317e+02,
       7.87641389e-01, 4.88852266e+01, 8.15035670e-01, 1.19893112e+01,
       7.27087901e+01, 8.76150126e+00, 1.20750164e+01, 8.13976478e+00,
       2.35244488e+00, 3.91378082e-03, 6.77553501e+00, 2.90931629e+00,
      

In [18]:
y_hat 

array([21.58039261, 10.60377648,  3.64188551, 27.66420262,  9.07478088,
       23.11471474, 24.90387541, 25.35290294, 24.67880828, 19.59554846,
       11.65559518, 19.78405675, 31.40374747, 15.61040592, 22.27630713,
       18.79060918, 12.57703266, 26.99846172, 19.6044484 , 22.67074129,
        9.49632961, 35.47912519, 36.19943176, 26.274562  , 23.5421998 ,
       23.07304839, 12.9623829 , 26.29418024, 14.72143939, 37.83327915,
       33.09338073, 21.70531809, 28.26874447, 44.07308696, 24.75804971,
       19.85191196, 20.78767799, 24.14193718, 36.18000261, 14.30341899,
       21.84989416, 13.71621233, 29.15645376, 23.99432145, 24.28749163,
       20.29179709, 20.89720674, 11.73744152, 24.47305506, 22.75998332,
       21.02508757, 22.1530273 , 30.5337682 , 13.33743978, 25.80298579,
       16.0056718 , 30.80999501, 34.2782629 , -1.31617156, 30.8028857 ,
       22.09571165, 21.15654809, 16.16034836, 22.79354791, 18.28867859,
       20.23806963,  8.55123947, 25.33311168, 19.32907647, 24.47

In [9]:
idx[-200:]

array([ 27, 107,  44, 186, 279, 258,  53, 178, 233, 294, 288,  82, 129,
       342, 106,   4, 423, 253, 212,  77, 493, 409,  21, 362,  81, 439,
       200, 422, 190, 300, 231,  87, 400,  39, 350, 408, 453, 483, 452,
       167, 351, 407, 333, 427, 287, 115, 317, 370, 404, 125, 480, 433,
        69, 168,  89, 119, 216, 118, 255,   8, 346, 446, 189,  35,  75,
       193, 315,  28,  95, 358, 344, 442, 313, 348, 273,  23, 262, 499,
       414,  47, 292,  29, 430,  61, 456, 417,  42,   5, 232, 311, 173,
       478,  65,  40, 205, 108,  67,  34, 481, 345, 402, 390, 210, 405,
         6,  97, 326, 363, 198, 306, 377, 146,  73, 127, 415, 281, 172,
        78,  84, 458,  49, 460, 412, 120, 455, 365, 297, 153,  52, 133,
        94, 267, 213, 397,  56, 224, 465, 435, 175, 101, 334, 320, 244,
       285, 159, 165,  57, 261,  79, 497, 195, 401, 484, 137, 467, 443,
       291, 174, 211, 103, 112, 372, 496, 139, 416, 132, 266, 220,   0,
        80, 330, 204, 149, 138, 501, 121, 236, 316,  63, 310,  5